language: python
services:
  - docker
env:
  global:
    - IMAGE_NAME=skyuk/docker-registry-exporter
    - GOSS_VERSION=0.3.5
    - GOSS_PATH=/usr/local/bin/goss
    - secure: "WxEWtTPLJSMzEPiyLM0ti0qcJf1s3OSo0ldYDqIqCRSN1Nfwdj/O1o5UKMItg9Fus5H/u9vgDK+I+JmjWVMy3rTir47wYqv0NRdkQZF1U9QjRoEvz6I+rF3mPgSwk11Kp3bfFO98u5RLY4PpZxyYvCpGqfbyBywg+to21x+o/NNGyAhr2JGGR33ycj9Qhr04I74tnXKsPA11IVzsMjfyuM4n5+JobIXmkv4kL7Zl/eI2BMTRdkaCLYW9tPdPrCPTFqhPYmh8TBj1MAcmK+SUNj3/je/Pcsml/gFVhzoe9CrccHTpRhC9sTCkWHJNp9uDHwCh03IBenCvM1W/zdK8soybGv3iU47xM/bSykHBP7BIQzrh4Lqk+4lJqnNJYx657znpskzWlBvyIEm2uEPCQMk9Yn44Ltye4r9IInNsHksV9GatvSoTAPRkRf1V/TRoplcfu28+ZbqYXHH5CkrM3tHqiTksg4U38RbhtHCDG5FHjDXYNPpxADb7Y819niVXwS2QNmCHxe8z8GppK12fPVcYZw95krz5m0qTtU6vQFGXSse+Pda96OMLTw8FujRQ0A63W+koKZckS/noL4NknS+xI+FCcFj8s3eRaCuQb4aDkjS4+KmL6Q9osnQROKjPQDlcUU7dpnHwoJBAf6jNyBl/KJKm8DOlt4v3Ndt3ktU="
    - secure: "nGIrTKN7f0g478n9XBeX3U3BwhDcGvJ9kK8YojGGSnTNv6ORs78Z3rhipiQX8OKh3/2q1oz+SPm3cwRBaqd0Jrbm9QMmUTMXsqSSezx2PNOniMVGNhbj0/IVLkSGR0kvjCHkEqmApDXvIGYdbHxmq1esBoyggKVddneolk+OXtwAkC8BKBv9YqC9ed67acpzqUpuGbLKUVQmdTnijFHt3kLqWgE8jpoFmNUI4b3H0uTJSdJJX2Fmf1mnKsS9SWPk0yqf7VlBgVkuA4tgkfUMugGqDR0NQRhRjyqmdy31bRJ44MFPcEUUI8TWZjXxdDQcTE3Udysj2VP99kNsB1rBvQk6BQjdAKVN3WHsvnukyhqmbsd5btOi5F0jlPlSsqp/Ao93Z4/H5aQzjFza7MMjNS4H3PrntkXdxsvTvProBdlamtY7MWhq7boVjn3E/BJ1J/IzqtWQXJlIwUMfEwXG8dZA7KrScMrMhp4vcCHkdhp1LE7PatVIKzDyoveDkiWlbYJbqirb4antQAGJlEkDBfHqs3Eow/G7y5bWBl2sG/vZhAl30YQeZ39kGSekEpF2vVUPn+R4YcvVB97XzUoCzLKkBmOkFHfInpu5dE63SvGgeVtyHc3AhiJAq1TPdUFrutq5jdjnOUMONG4ccuzEb0YW/YQvfX40YUMogR7emTc="
python:
  - "3.6"
before_install:
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/dgoss -o /usr/local/bin/dgoss
  - sudo chmod +rx /usr/local/bin/goss
  - sudo chmod +rx /usr/local/bin/dgoss
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
  # Ensure the script obeys PEP8 style guide
  - flake8 --max-line-length=120 exporter/
  # Run unit tests
  - pytest
  # Check coverage of unit tests and fail if <80%
  - pytest --cov=exporter
  # Run static code analysis for common security issues
  - bandit exporter/*.py
  # Check licenses of dependencies are permissive
  - liccheck -s strategy.ini
  # Check dependencies for known vulnerabilities
  - safety check -r requirements.txt
  # Package docker application
  - docker build -t ${IMAGE_NAME} .
  # Run integrated test
  - dgoss run -v ${PWD}/integrated-test:/repositories ${IMAGE_NAME} /repositories
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker-ci-deploy --version "$TRAVIS_TAG" --version-semver --version-latest "$IMAGE_NAME"
  on:
    tags: true
